#ifndef MASKCOUT_CONFIG_H
#define MASKCOUT_CONFIG_H
#define MASKCOUT_VERSION_MAJOR 0
#define MASKCOUT_VERSION_MINOR 1
#define MASKCOUT_VERSION_PATCH 0
#define MASKCOUT_PAGE_SIZE 4096u
#define MASKCOUT_HEAP_SIZE (1024u * 1024u)
#define MASKCOUT_MAX_TASKS 64u
#define MASKCOUT_MAX_PROCESSES 32u
#define MASKCOUT_IPC_CAPACITY 64u

#endif
